"""scripts table

Revision ID: 99d6881f2f6a
Revises: e8c4255c72fd
Create Date: 2019-01-21 21:03:22.474337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d6881f2f6a'
down_revision = 'e8c4255c72fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script', sa.Column('parameters', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('script', 'parameters')
    # ### end Alembic commands ###
